/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


#include <stdio.h>
#include "UART.h"
#include "Temp_int.h"

#define SCB_CPACR   (*(volatile uint32_t*)0xE000ED88U)

uint16_t Data1=0;
float Temp=0;

void delay(void)
{
	for(uint32_t i=0;i<250000;i++);
}
int main(void)
{
	SCB_CPACR |= (3UL << 20) | (3UL << 22);

	uart2_tx_init();
	ADC_Init();
	ADC_Interruptconfig();
	ADC_Start();

	while(1)
	{
		delay();
		int32_t t = Compute_temp_x100(Data1);

		printf("ADC value: %d | Temperature: %ld.%02ld C\r\n",Data1, t/100, abs(t%100));


	}
}

void ADC_IRQHandler(void)
{
	ADC_IRQ_Handler(&Data1);

}
