/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


#include <stdio.h>
#include "UART.h"
#include "ADC_WatchDog.h"

uint16_t Data = 0;

void delay(void)
{
	for(uint32_t i=0;i<250000;i++);
}
int main(void)
{
	uart2_tx_init();
	LED_Init();
	ADC_Init();
	ADC_Interruptconfig();
    ADC_Watchdog();
	ADC_Start();

	while(1)
	{

		printf("ADC Values : %d\r\n",Data);
		delay();
	}
}

void ADC_IRQHandler(void)
{
	ADC_IRQ_Handler(&Data);
}
